- name: Hello Ansible - quick start
  hosts: 192.168.50.101
  user: vagrant
  sudo: yes

  tasks:
   - name: Provisionnement du service (NEXUS)
     action: shell docker run -d -p 8081:8081 --name nexus sonatype/nexus3
